"""Initial migration.

Revision ID: 22f3a1314f87
Revises: 
Create Date: 2024-07-22 16:38:43.739878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22f3a1314f87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedido')
    op.drop_table('item_pedido')
    op.drop_table('usuario')
    op.drop_table('produto')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('produto_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('preco', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('estoque', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='produto_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('usuario',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('usuario_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nome_usuario', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('senha', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='usuario_pkey'),
    sa.UniqueConstraint('email', name='usuario_email_key'),
    sa.UniqueConstraint('nome_usuario', name='usuario_nome_usuario_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('item_pedido',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_pedido', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_produto', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('preco', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedido.id'], name='item_pedido_id_pedido_fkey'),
    sa.ForeignKeyConstraint(['id_produto'], ['produto.id'], name='item_pedido_id_produto_fkey'),
    sa.PrimaryKeyConstraint('id', name='item_pedido_pkey')
    )
    op.create_table('pedido',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valor_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], name='pedido_id_usuario_fkey'),
    sa.PrimaryKeyConstraint('id', name='pedido_pkey')
    )
    # ### end Alembic commands ###
